/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./src/components/animation/AppBackground.vue')['default']
    AppFloatButton: typeof import('./src/components/layout/AppFloatButton.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppFriends: typeof import('./src/components/friends/AppFriends.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppHome: typeof import('./src/pages/home/index.vue')['default']
    AppSideBar: typeof import('./src/components/layout/AppSideBar.vue')['default']
    AppSignIn: typeof import('./src/components/sign-in/AppSignIn.vue')['default']
    AppSignUp: typeof import('./src/components/sign-up/AppSignUp.vue')['default']
    ChatFriends: typeof import('./src/components/friends/ChatPanel.vue')['default']
    ChatPanel: typeof import('./src/components/friends/ChatPanel.vue')['default']
    Details: typeof import('./src/components/games/Details.vue')['default']
    DropMenuHover: typeof import('./src/components/ui/DropMenuHover.vue')['default']
    FormGames: typeof import('./src/components/form/FormGames.vue')['default']
    FriendsList: typeof import('./src/components/friends/FriendsList.vue')['default']
    Hero: typeof import('./src/components/generic/heros/hero.vuero.vue')['default']
    HeroDefault: typeof import('./src/components/generic/heros/HeroDefault.vue')['default']
    HerosAnimation: typeof import('./src/components/generic/heros/HerosAnimation.vue')['default']
    ModalFriends: typeof import('./src/components/friends/FriendsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTheme: typeof import('./src/components/ui/SelectTheme.vue')['default']
    Sing: typeof import('././src/components/ui/selectTheme.vue]
    Switch: typeof import('./src./src/components/ui/selectTheme.vueefault']
    SwitchTheme: typeof import('./src/components/ui/SwitchTheme.vue')['default']
    UserProfileModal: typeof import('./src/components/modals/UserProfileModal.vue')['default']
    VIconsAnimation: typeof import('./src/components/animation/VIconsAnimation.vue')['default']
    VPulseStars: typeof import('./src/components/animation/VPulseStars.vue')['default']
    VshootingStars: typeof import('./src/components/animation/VShootingStars.vue')['default']
    VShootingStars: typeof import('./src/components/animation/VShootingStars.vue')['default']
  }
}
