/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFloatButton: typeof import('./src/components/layout/AppFloatButton.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppHome: typeof import('./src/pages/home/AppHome.vue')['default']
    AppSideBar: typeof import('./src/components/layout/AppSideBar.vue')['default']
    AppSignIn: typeof import('./src/components/sign-in/AppSignIn.vue')['default']
    AppSignUp: typeof import('./src/components/sign-up/AppSignUp.vue')['default']
    DropMenuHover: typeof import('./src/components/ui/DropMenuHover.vue')['default']
    Hero: typeof import('./src/components/generic/heros/hero.vuero.vue')['default']
    HeroDefault: typeof import('./src/components/generic/heros/HeroDefault.vue')['default']
    HerosAnimation: typeof import('./src/components/generic/heros/HerosAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sing: typeof import('./src/pages/sing/Sing.vue')['default']
    VIconsAnimation: typeof import('./src/components/animation/VIconsAnimation.vue')['default']
    VPulseStars: typeof import('./src/components/animation/VPulseStars.vue')['default']
    VshootingStars: typeof import('./src/components/animation/VShootingStars.vue')['default']
    VShootingStars: typeof import('./src/components/animation/VShootingStars.vue')['default']
  }
}
