/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/completed/AppCompleted': RouteRecordInfo<'/completed/AppCompleted', '/completed/AppCompleted', Record<never, never>, Record<never, never>>,
    '/dashboard/AppDashboard': RouteRecordInfo<'/dashboard/AppDashboard', '/dashboard/AppDashboard', Record<never, never>, Record<never, never>>,
    '/favorites/AppFavorites': RouteRecordInfo<'/favorites/AppFavorites', '/favorites/AppFavorites', Record<never, never>, Record<never, never>>,
    '/games/AppGames': RouteRecordInfo<'/games/AppGames', '/games/AppGames', Record<never, never>, Record<never, never>>,
    '/history/AppHistory': RouteRecordInfo<'/history/AppHistory', '/history/AppHistory', Record<never, never>, Record<never, never>>,
    '/home/AppHome': RouteRecordInfo<'/home/AppHome', '/home/AppHome', Record<never, never>, Record<never, never>>,
    '/login/Login': RouteRecordInfo<'/login/Login', '/login/Login', Record<never, never>, Record<never, never>>,
  }
}
